apiVersion: v1
kind: ConfigMap
metadata:
  name: solidarytech-config
  namespace: solidarytech
data:
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/919675276626/solidary-donations"
  AWS_DYNAMODB_TABLE: "SolidaryTechVolunteers"
